PXZ strong site closed since 2018 - PWZ strong replaces
GeoNet/delta pull request #1150
Opened 2021-08-22 22:47 UTC by salichon

2018 Legacy - see ticket

2021-08-22 23:30 UTC, CBurton90 submitted a review, later dismissed

2021-08-22 23:40 UTC, mnaguit requested changes
Data for BN* at LC 20 for PXZ still available up to 2018.087.

```
miniseed/2018/2018.087/PXZ.NZ/2018.087.PXZ.20-BNE.NZ.D
miniseed/2018/2018.087/PXZ.NZ/2018.087.PXZ.20-BNN.NZ.D
miniseed/2018/2018.087/PXZ.NZ/2018.087.PXZ.20-BNZ.NZ.D
```

2021-08-23 02:10 UTC, salichon commented
- PXZ slates removed by  2018-01-17T05:30:00Z
- PXZ SM stopped by  28 March 2018 02:00 UTC

2021-08-23 02:25 UTC, CBurton90 approved these changes

2021-08-23 02:26 UTC, mnaguit approved these changes
👍

2021-08-23 03:00 UTC, merged