update connections to allow for a datalogger pin offset
GeoNet/delta pull request #1324
Opened 2022-05-01 05:43 UTC by ozym

One of the trickier part with building equipment response meta data is handling the exceptions, in this example the Quanterra Q330HR series has a different channel response depending on whether the first bank (0-2) or second bank (3-5) channels are used. Normally the broadband (high resolution) sensor will be plugged into the first bank, and the strong motion will be the second.

This PR adds the ability to indicate which bank (or channel) the sensor has been plugged into on the datalogger. In most instances this will be zero as the number of datalogger channels matches the number of sensor components, or at least they both start at zero.

Where there are two sensors attached to a single datalogger, the offset will not be needed unless the datalogger has a different response for any channels (as per the Q330HR) or if the full calibration details of the datalogger are to be included. The last part will be required to match the sensor with the datalogger channel.

The follow on from this PR will be:

- to update any downstream applications that may use a `connections.csv` file (mostly for testing)
- look at adding a Channel (or Pin) column in the `calibrations.csv` file to allow for datalogger calibration (if needed).

2022-05-01 05:48 UTC, ozym commented
This is likely to cause a merge conflict with any outstanding PRs that adjust the `connections.csv` file.

2022-05-02 21:23 UTC, salichon commented
thanks !
work in progress i suppose. 

So  Offset in Delta is the start of the  first bank (0-2) or second bank (3-5) channels (either 0 and 3 (ideally) 
(as far as i understand then once the Offset is given. this will point to the build of the datalogger yaml
for which a response by offset will be  created)

2022-05-02 22:10 UTC, ozym commented
Yes, @salichon this is the first step in a chain of updates needed to make the response generation a lot simpler.

I wasn't sure whether to use the work "Pin" as historically a datalogger had its channels defined as "pins" (like in a cable plug) this is to distinguish between a "Channel" code as used in say the FDSN "channel" naming convention.

We can change this later as it's only used in the header and code, not the data.

It also means we can add different sensors to different parts of the dataloggers, if we are worried about datalogger calibrated values rather than the nominal sensitivities.

2022-05-03 02:38 UTC, ozym commented
I've switched to using "Pin", this is to avoid using Offset which is used elsewhere related to sensor offsets from a position.

The "Pin" is the lowest channel number which matches the lowest sensor component number (i.e. a 6 channel Q330 has pins 0 to 5, and a broadband sensor as 3 components, 0 to 2.  So the Pin will be 0 if plugged into bank A (0-2), or 3 if in bank B (3-5).

2022-05-04 21:56 UTC, salichon commented
cool  
Some of the `connections.csv` in the PR  are still using "offset" label in place of "pin" is it correct  for these case (tools or tests) ?

2022-05-04 23:02 UTC, ozym commented
@salichon good spotting, these are just for testing other things so don't flag as a problem.  I have updated them.

2022-05-17 21:56 UTC, CBurton90 commented
@ozym I understand this links sensors to digitiser bank (0 or 3) but for those circumstances where the bank is set with a different number of bits (e.g., 24bit vs 26bit Q330HR) where is the actual bit weight value (counts > V) stored for the response creation?

2022-05-17 23:36 UTC, ozym commented
@CBurton90 that will be left to the response label as found in  #1325

2022-05-17 23:53 UTC, CBurton90 submitted a review, later dismissed

2022-05-18 01:00 UTC, elidana requested changes
Hi @ozym ,

sorry for being slow here. At a first pass looks good to me. With a small change in the connections.csv header.

A couple of other comments that can be addressed at a later stage:
1. I would like to find a different name than pin, but agree that channel is overloaded and not ideal. This is not crucial now, so happy to merge this and having some name party later on (but soon enough not to cause too much disruption).

2. is it worth adding a test that checks that "pin" is only used when necessary? not sure how this can be done in a programmatic way. I'm thinking along the lines of ensuring that:
- only inital pin in a bank is inserted
- only pin with a "meaning" are insterted
- format is what the code that create the response file would expect (integer value, 0 or 3)

3. we need to add some documentation around that, but I think this can come to the end, once we have captured all use cases and scenarios (geomag, quanterra dataloggers, possibly envirosensors, etc).

2022-05-18 01:00 UTC, elidana commented on install/connections.csv
> +Station,Location,Place,Role,,Start Date,End Date
change to 
`Station,Location,Place,Role,Pin,Start Date,End Date`

2022-05-18 03:39 UTC, salichon commented
_- FAIL: TestConsistency/check_file_consistency:_connections (0.00s)
        consistency_test.go:39: unexpected connections.csv content -got/+exp_
        
Can this be the header name ?

2022-05-18 04:33 UTC, ozym commented
@elidana the pin is only added when it's needed.  If no pin is given then it defaults to 0

2022-05-18 04:35 UTC, ozym commented
Happy to use another word that means the wire coming out of the sensor cable plug is attached to the wire in the datalogger cable plug.  (where there's not much standard in how they are numbered or sometimes letters are used).

2022-05-23 00:26 UTC, elidana commented
I heard @CBurton90 using "bank" terminology to describe Centaur dataloggers and cabling.

have tried to have a look at the IRIS response library to see if they use a specific terminology but couldn't find anything obvious.

In the case of a fluxgate (and possibly LRDCP?) we cannot use too many standards probably, considering that a "pin" can directly relate to the measure that is done using a given sensor. In our first attempt for EYRW, we were using pin 0-2 for the XYZ component, and pin 3 for the temperature sensor. 

Let's try pin for now. I guess we will need to iterate a few times

2022-05-23 00:27 UTC, elidana approved these changes

2022-06-26 05:52 UTC, ozym commented
To try and move this along a bit, I have replaced the word "Pin" with the word "Number".

2022-07-01 03:40 UTC, elidana commented
Hi @ozym ,
happy for this to be merged.

Perhaps when we will continue this body of work, is it worth looking at nomenclature used within StationXML and (in particular) the concept of source and subsource as in http://docs.fdsn.org/projects/source-identifiers/en/v1.0/channel-codes.html? 

But please merge away (from the little of my knowledge here)

2022-07-01 03:40 UTC, elidana approved these changes

2022-07-01 03:54 UTC, ozym commented
> Hi @ozym , happy for this to be merged.
> 
> Perhaps when we will continue this body of work, is it worth looking at nomenclature used within StationXML and (in particular) the concept of source and subsource as in http://docs.fdsn.org/projects/source-identifiers/en/v1.0/channel-codes.html?
> 
> But please merge away (from the little of my knowledge here)

Yes, we need to think about that, but it's still more aimed at the miniseed side of things (as recorded) which is still a work in progress. The stationxml part: http://docs.fdsn.org/projects/stationxml/en/latest/reference.html#channel  will still have a "Code" which may end up the same, but will probably not use those names just yet.  But this is the direction things are going, see the "sourceID" at the bottom as an example of that.

2022-07-01 03:55 UTC, merged