add citations poc
GeoNet/delta pull request #1424
Opened 2022-08-21 01:03 UTC by ozym

The work on polarities has indicated that there will be a need for some mechanism for citing references or other associated external information.

To this end, I've made an example "citations.csv" formatted table. I've placed it under the `references` folder for want of anything else.  I haven't used the word "reference" in the names as this clashes with the use of this term for defining where something is, i.e. with reference to this point.

I've also started looking at adding a DOI mechanism. This may be expanded as needed or appropriate to other tables. especially the network table.

This mechanism should also be able to present "web" type links so, other than the key, all fields should be optional.

I haven't defined a "key" style, but the constraints are that it be unique, and the table will be sorted based on this value. I was thinking of a short style, or "<author><year><series>" where author can be a lowercase or abbreviated name, the year is optional and the series (e.g. "a", "b", "c") may be able to distinguish multiple publications in a given year.

This is aimed as a starting point of discussion. the code has been written as a proof of concept but not included.

2022-08-21 21:17 UTC, mnaguit submitted a review, later dismissed
Thanks @ozym . This is great! 👍

2022-08-21 21:19 UTC, rumachan requested changes
Only suggestion is a little bit more explanation of when quotes might be required, i.e. when the text, usually the title or author list, contains commas.

2022-08-22 00:38 UTC, ozym commented
@rumachan I've updated the README to reflect the comma situation.

2022-08-22 01:11 UTC, rumachan approved these changes
All good

2022-08-22 02:52 UTC, salichon approved these changes
all good to me for this template

2022-08-22 03:06 UTC, mnaguit approved these changes

2022-08-22 20:36 UTC, staylorofford reviewed
Looks good. Just wondering where the citations for this table will occur in the metadata or delta CSVs?

2022-08-30 23:18 UTC, merged