add component and channel docs
GeoNet/delta pull request #1460
Opened 2022-09-29 20:35 UTC by ozym

2022-09-29 23:23 UTC, salichon approved these changes
Great - good to me  in practice for a change/additon 
- the _sensor component  "number"_ has to be explicit  (always  0,1,2 .... )
- the _datalogger channels "number"_ can be implicit (default to 0) 
and its value should be m,most of the time   0 or 3

2022-09-30 00:44 UTC, elidana requested changes
Hi @ozym , this looks good to me, but I think a couple of minor changes are needed, as I think the info in the README seems to be now duplicated (see detailed comments below).

2022-09-30 00:44 UTC, elidana commented on install/README.md
> +* `channels.csv` - Individual datalogger recording elements including digitiser position, sampling rate, and responses.
minor change in the README, this is a duplication of line n.26

2022-09-30 00:44 UTC, elidana commented on install/README.md
> +    Guralp,Fortis,Accelerometer,2,E,0,90,G,sensor_guralp_fortis_response
this section to describe `components` is already present in the paragraph below (after "CALIBRATIONS"), shall one of the two be removed from the README?

2022-09-30 00:44 UTC, elidana commented on install/README.md
> +    Quanterra,Q330HR/6,Datalogger,3,200,datalogger_quanterra_q330_200_response
same as above, is that section now a duplicate in the README?

2022-09-30 01:48 UTC, closed without merging

2022-09-30 02:47 UTC, elidana commented
uh not sure if there were new things, I'll have a quick look and raise a new pr if I notice something.

2022-09-30 02:56 UTC, elidana commented
the only difference this one was adding are the examples, but since all other descriptions in the README won't have one, I think we can leave it as is and we can always use the files in `meta/testdata` for reference, and until the channels and components tables are built.