add collection code to set
GeoNet/delta pull request #1537
Opened 2022-11-17 23:03 UTC by ozym

This code joins the dataloggers, the sensors, and the streams for the times when they overlap.  There is also provision for times which may need adjustments (i.e. gains, polarities) which may not relate to the physical connections between the various parts.

This is the engine for building stationxml like meta data.

2022-11-22 22:35 UTC, bpeng commented on meta/collection.go
> +
don't know if I fully understand the logic, but seems the `gains`, `sensors` and `dataloggers` are not dependent on `channels`, and can be calculated outside the channels loop L155

2022-11-22 22:37 UTC, bpeng commented on meta/collection.go
> +							})
similar to the above, check if it is possible to calculate `gains` and `sensors` out side the channels loop

2022-11-22 22:38 UTC, bpeng requested changes
Code looks tidy, little check

2022-11-23 19:52 UTC, ozym commented
@bpeng I did a recheck and found there should be an extra constraint for the sensor/datalogger calibrations for the Number. These files should have the Number explicitly given (as it's a calibration).

I've also adjusted the order of the loops to make the time span get evaluated as soon as possible, and to be consistent for both sets.

2022-11-23 20:08 UTC, bpeng approved these changes
OK

2022-11-23 20:09 UTC, merged