add response decoder
GeoNet/delta pull request #1618
Opened 2023-02-03 11:21 UTC by ozym

This PR follows on from the encoder work.

Given a byte representation of an XML file, the decode will, depending on required version, extract the appropriate parts and return a cleaned byte slice. This code is primarily used to compare two different StationXML files and attempts to make the options uniform allowing comparisons.

2023-02-08 21:23 UTC, bpeng commented on internal/stationxml/decoder10.go
> +				}
the above 5 loops can be combined into 1, use something like
```
if stage.Polynomial != nil {
	stage.Polynomial.Name = ""
	stage.Polynomial.ResourceId = ""
}
...
```

2023-02-08 21:43 UTC, bpeng commented on internal/stationxml/decoder10.go
> +		}
channels are not sorted as version11&12, is this intentional?

2023-02-08 21:46 UTC, bpeng requested changes
code looks good, small suggestions
separate structs for 3 versions have duplicate code, not sure if it is feasible to use one struct

2023-02-08 22:03 UTC, ozym commented
The duplicate code is related to importing different modules. Will update other comments.

2023-02-09 00:45 UTC, ozym commented
@bpeng have updated code.

2023-02-09 03:39 UTC, bpeng approved these changes
OK

2023-02-09 03:57 UTC, merged