NEZ Sensor EH to HH change + Datalogger bank Swap + New loc code to 12
GeoNet/delta pull request #1643
Opened 2023-03-03 03:52 UTC by salichon

2023-03-03 04:53 UTC, mnaguit requested changes
Thanks @salichon . Here, a few suggested edits:
- streams at LC 12 (True for axial flag in `install/streams.csv`)
- is there a need to update the orientation of the sensor at LC 12? (in `install/sensors.csv`)

2023-03-05 21:04 UTC, CBurton90 requested changes

2023-03-05 21:04 UTC, CBurton90 commented on install/streams.csv
> +NEZ,12,H,H,100,false,false,false,2023-02-28T22:51:00Z,9999-01-01T00:00:00Z
`NEZ,12,H,H,100,true,false,false,2023-02-28T22:51:00Z,9999-01-01T00:00:00Z`

2023-03-06 02:01 UTC, salichon commented
thanks @CBurton90 @mnaguit 
corrected PR 
The aZimuth of NEZ 12 will come later -we can track this in the ticket  when necessary  - iis it ok ?

2023-03-06 04:54 UTC, mnaguit approved these changes
All good Sir! Thanks! 👍

2023-03-08 20:23 UTC, CBurton90 approved these changes

2023-03-09 01:03 UTC, salichon commented
Will  uadte azimuth when known :)

2023-03-09 02:43 UTC, merged