WTAZ open LC 13
GeoNet/delta pull request #1694
Opened 2023-05-15 05:43 UTC by mnaguit

- borehole sensor: TH120PH-2 (9205)
- depth (90m) & orientation (36)
- For LC 13 (HH/LH-12Z) streams

Can you please double check the sensor details for this one? Thanks @CBurton90

2023-05-15 20:28 UTC, CBurton90 commented
@mnaguit `TrilliumCompact 9205` (Trillium Compact 120PH-2) is correct

2023-05-15 20:30 UTC, CBurton90 approved these changes

2023-05-15 23:04 UTC, salichon requested changes
WTAZ HH 13 azimuth :)

2023-05-15 23:04 UTC, salichon commented on install/sensors.csv
Need sensor borehole  loc 13  orientation to  ~36 or 39 degrees
thanks

2023-05-15 23:10 UTC, mnaguit commented on install/sensors.csv
Yay. Thanks @salichon . Entry has been modified for azimuth.

2023-05-15 23:15 UTC, mnaguit commented
Another round of review, please Gentlemen! 
Thanks!

2023-05-15 23:31 UTC, CBurton90 approved these changes

2023-05-16 01:39 UTC, salichon approved these changes
ouioui

2023-05-16 01:40 UTC, merged