PNUZ new RCET station
GeoNet/delta pull request #1696
Opened 2023-05-16 22:26 UTC by mnaguit

- TC120PH-2 (SN 3816) for LC 10 (LH/HH-ENZ streams)
- Fortis (TF1126) for LC 20 (HN-ENZ streams)
- Centaur firmware v4.5.20

Is the network code `RA`? @CBurton90 @salichon

2023-05-16 22:41 UTC, CBurton90 commented
@mnaguit Is it worth including @staylorofford in the reviews for the RCET sites? I know the majority should have been installed in a shallow posthole vault so we might need some consistency in regards to depth (but perhaps `0` is fine and that's ok with me 😄 )

2023-05-16 22:41 UTC, CBurton90 submitted a review, later dismissed

2023-05-16 22:44 UTC, mnaguit commented
Hi @staylorofford . We will include you in all RCET delta reviews, so you can have a good look of the delta nitty-gritty.

2023-05-16 23:01 UTC, staylorofford commented
Hold fire on merging this - I will check the depth with Brendong

2023-05-16 23:14 UTC, CBurton90 commented
@staylorofford Was there a standardize depth planned for all RCET sites or were they designed to vary slightly location dependent (or how the contractor actually built the vault)? Just wondering if there is a "blanket" value we can put in for all the sites so it represents them nicely.

2023-05-16 23:31 UTC, staylorofford commented
SM sensor is at 0 m (loc 20) while WM sensor is at 1.2 m (loc 10)

2023-05-16 23:31 UTC, staylorofford requested changes
See above

2023-05-16 23:49 UTC, staylorofford commented
@CBurton90, all weak motion sensors should be at 1.2 m install depth, all strong motion will be at 0 m. The contractors drilled to specification 1.2 m on all sites.

2023-05-16 23:49 UTC, mnaguit commented
Sensor depth for TC120PH-2 updated to 1.2m

2023-05-16 23:59 UTC, staylorofford approved these changes
I approve these depths.

2023-05-17 03:07 UTC, salichon requested changes

2023-05-17 03:07 UTC, salichon commented on install/connections.csv
I reckon it would be better to  set the connection numbers when using  the dataloggers with multichannels now 
 to me this can be good practice
(but need to remember .. :) ) 
 so far i don think there are any impacts though  for this mount

2023-05-17 03:28 UTC, mnaguit commented on install/connections.csv
entry corrected

2023-05-17 20:59 UTC, mnaguit commented
Waiting for 3 👍 on this one, before I issue another PR for the other RCET (KBRZ). FYI Gentlemen!

2023-05-17 22:11 UTC, CBurton90 approved these changes

2023-05-18 01:13 UTC, salichon approved these changes
cool  as ;)

2023-05-18 01:31 UTC, merged