ROTS recorder swap
GeoNet/delta pull request #1707
Opened 2023-05-22 03:27 UTC by mnaguit

- from CUSP3D (42006) to EQR120 (46503)
- for LC 20 (HN-12Z) streams

Hi @CBurton90 , is the firmware version for EQR120 v2.2.2? Thanks!

2023-05-22 04:12 UTC, Thomas-Benson submitted a review, later dismissed
Looks good to me

2023-05-22 04:18 UTC, CBurton90 commented
@mnaguit yes 2.2.2

2023-05-22 04:18 UTC, CBurton90 submitted a review, later dismissed

2023-05-22 04:52 UTC, mnaguit commented
Hi @CBurton90 @Thomas-Benson 
Travis error fixed. Another thumbs up please? Thanks!

2023-05-22 21:12 UTC, CBurton90 submitted a review, later dismissed

2023-05-22 21:59 UTC, salichon requested changes
just a bit opf polishing :)

2023-05-22 21:59 UTC, salichon commented on install/streams.csv
ROTS is no more triggered since 202.040  (february  2020) 
it s a bit  better for consitsency  withthe other ones (information)

2023-05-22 21:59 UTC, salichon commented on install/recorders.csv
Out of precaution and since the azimuth is 90 and the SM boxes are different
would you check that the orientation has been kept the same and not shifted  90deg between components. 
Thanks

2023-05-22 22:06 UTC, mnaguit commented on install/streams.csv
Yes that is right. But because of the 20 hour gap from this recent recorder swap, I opted to use this gap in updating the entries. Nevertheless, if consistency is the key, will use the 'standard' 200hz end-start.

2023-05-22 22:08 UTC, mnaguit commented on install/recorders.csv
Hi @CBurton90 . Can you please double checking the azimuth? Thanks!

2023-05-23 00:09 UTC, CBurton90 approved these changes
Approving in anticipation azimuth is the same (will wait for Cameron's comment in the ticket).

2023-05-23 02:13 UTC, salichon approved these changes

2023-05-23 02:14 UTC, merged