DUWZ Q330-Centaur datalogger swap
GeoNet/delta pull request #1749
Opened 2023-06-19 22:00 UTC by Thomas-Benson

- Replaced Kinemetrics Q330/6 (2035) with Nanometrics Centaur CTR4-6S (9869)
- Streams affected EH-ENZ & HN-ENZ

2023-06-20 00:47 UTC, CBurton90 requested changes

2023-06-20 00:47 UTC, CBurton90 commented on assets/dataloggers.csv
> +nanometrics,Centaur CTR4-6S,9869,,
Missing caps

2023-06-20 01:04 UTC, Thomas-Benson commented on assets/dataloggers.csv
> +nanometrics,Centaur CTR4-6S,9869,,
Fixed typo

2023-06-20 02:05 UTC, salichon approved these changes
sweet

2023-06-22 02:21 UTC, CBurton90 approved these changes

2023-06-22 02:45 UTC, merged