WNPS Strong motion sensor swap
GeoNet/delta pull request #1757
Opened 2023-06-21 21:16 UTC by Thomas-Benson

- Removed SCI CSUP3D (42040) from location 20 HN-12Z
- Replaced with CSI EQR120 at same location
- Firmware version 2.2.2, is this right?
- This station has been continous since 2020-02-09T21:50:00

2023-06-22 00:02 UTC, salichon approved these changes

2023-06-23 03:47 UTC, CBurton90 commented
@Thomas-Benson Firmware is `2.3.2` (should be that for all new EQR120's going out)

2023-06-23 03:48 UTC, CBurton90 requested changes
Looks good after fw correction : )

2023-06-23 03:48 UTC, CBurton90 commented on install/firmware.csv
> +Canterbury Seismic Instruments,EQR120,46499,2.2.2,2023-06-21T00:01:00Z,9999-01-01T00:00:00Z,
2.3.2

2023-06-23 03:53 UTC, Thomas-Benson commented on install/firmware.csv
> +Canterbury Seismic Instruments,EQR120,46499,2.2.2,2023-06-21T00:01:00Z,9999-01-01T00:00:00Z,
fixed firmware

2023-06-23 04:11 UTC, CBurton90 approved these changes

2023-06-26 21:30 UTC, mnaguit approved these changes

2023-06-26 21:44 UTC, merged