PRGZ Q330/3+L4C-3D to Centaur+LE-3Dlite Mk3 swap
GeoNet/delta pull request #1764
Opened 2023-06-28 21:53 UTC by Thomas-Benson

- Removing Q330/3 (2366) datalogger and L4C-3D (2991) sensor
 - Replacing with Centaur (9889) and Le-3Dlite MkII (G-0555)
 - Using most recent Centaur firmware version 4.8.5
 - Streams affected loc 10 EH-ENZ

2023-06-28 23:31 UTC, salichon submitted a review, later dismissed
ta!

2023-06-29 23:47 UTC, mnaguit requested changes
Sensor is `MKIII` (instead of `MKII`)

Thanks @Thomas-Benson

2023-07-02 21:07 UTC, Thomas-Benson commented on assets/sensors.csv
> +Lennartz Electronic,LE-3DliteMkII,G-0555,,
Fixed, sorry

2023-07-02 21:08 UTC, Thomas-Benson commented on install/sensors.csv
> +Lennartz Electronic,LE-3DliteMkII,G-0555,PRGZ,10,0,,0,0,0,0,0,0,2023-06-26T20:28:00Z,9999-01-01T00:00:00Z
Also fixed

2023-07-02 21:12 UTC, salichon approved these changes
sweet

2023-07-02 21:29 UTC, mnaguit commented on assets/sensors.csv
> +Lennartz Electronic,LE-3DliteMkII,G-0555,,
Thanks @Thomas-Benson 👍

2023-07-02 21:30 UTC, mnaguit approved these changes

2023-07-03 23:51 UTC, CBurton90 approved these changes

2023-07-04 02:40 UTC, merged