VGET - Alloy to Alloy receiver swap
GeoNet/delta pull request #1832
Opened 2023-09-03 23:25 UTC by aleks-spes

GNSS receiver swap: Alloy to Alloy at VGET station

2023-09-03 23:50 UTC, elidana requested changes

2023-09-03 23:50 UTC, elidana commented on install/receivers.csv
>  Trimble Navigation Ltd.,TRIMBLE ALLOY,6139R40213,VGET,2023-01-16T01:46:20Z,9999-01-01T00:00:00Z
I think this previous line was not deleted, this might be causing the test to fail?

2023-09-04 00:08 UTC, elidana approved these changes
looks good!

2023-09-04 01:14 UTC, gva6500 approved these changes
lgtm

2023-09-04 01:25 UTC, merged