PWES Basalt to TitanSMA SM recorder swap
GeoNet/delta pull request #1836
Opened 2023-09-05 20:47 UTC by Thomas-Benson

Removing Basalt (621) from PWES
Replacing with TitanSMA (2027) at same location
Using most recent TitanSMA firmware verison 4.5.22
Updated streams to reflect continuous streaming since `2020-02-09`

2023-09-06 01:58 UTC, gva6500 submitted a review, later dismissed
lgtm

2023-09-07 00:54 UTC, mnaguit requested changes
Should the Titan firmware start date be `2023-09-05T10:41:00Z`?

2023-09-07 01:35 UTC, Thomas-Benson commented
Fixed firmware opening time

2023-09-07 02:10 UTC, mnaguit approved these changes

2023-09-07 04:20 UTC, gva6500 approved these changes

2023-09-07 23:37 UTC, merged