WANS Basalt to EQR120 SM recorder swap
GeoNet/delta pull request #1837
Opened 2023-09-06 20:27 UTC by Thomas-Benson

- Removed Basalt (1673) from WANS LC 20
 - Replaced with EQR120 (46662) at same location
 - Using latest EQR120 Firmware version 2.3.2
 - Updated streams to reflect continuous streaming since `2020-02-09`

2023-09-06 21:19 UTC, gva6500 submitted a review, later dismissed

2023-09-07 00:36 UTC, mnaguit requested changes
for firmware, update the opening  time to `2023-09-06T00:14:00Z`? thanks @Thomas-Benson

2023-09-07 01:36 UTC, Thomas-Benson commented
Fixed this one as well, sorry for the double re-review requests.

2023-09-07 02:09 UTC, mnaguit commented
> Fixed this one as well, sorry for the double re-review requests.

No worries at all! 👍

2023-09-07 02:09 UTC, mnaguit approved these changes

2023-09-07 04:18 UTC, gva6500 approved these changes

2023-09-07 23:55 UTC, merged