PHHS Basalt to EQR120 SM Recorder Swap
GeoNet/delta pull request #1912
Opened 2023-11-16 22:36 UTC by Thomas-Benson

- Removing Basalt (1277) from PHHS LC 20
- Replacing with EQR120 (46661) at same location
- Using latest EQR120 firmware version 4.3.2
- Updated streams to continuous from 2020-02-09
- Streams affected: PHHS LC 20 HN-12Z

2023-11-16 23:06 UTC, mnaguit requested changes
tweak opening time of firmware, to match opening time of recorder

2023-11-16 23:06 UTC, mnaguit commented on install/firmware.csv
use opening time of recorder? thanks @Thomas-Benson

2023-11-16 23:30 UTC, Thomas-Benson commented on install/firmware.csv
Fixed, my bad for using the closing time instead.

2023-11-16 23:37 UTC, mnaguit commented on install/firmware.csv
All good @Thomas-Benson 😄

2023-11-16 23:38 UTC, mnaguit approved these changes

2023-11-20 21:52 UTC, gva6500 approved these changes

2023-11-20 22:14 UTC, merged