WQAB SM building array upgrade Cusp-Mes to EQR120s
GeoNet/delta pull request #2089
Opened 2024-06-12 20:46 UTC by Thomas-Benson

- Upgrading 16 Cusp-Me recorders to EQR120s
- Using EQR120 firmware version 2.3.2
- Updating stream codes from XYZ to 12Z
- All new recorders now have consistent orientation of 10 degrees

2024-06-12 23:33 UTC, mnaguit requested changes
Lots of work here, great job @Thomas-Benson , thanks! 👍 
To check: for `LC 2G`, the serial number from the main ticket is `46526`

2024-06-12 23:34 UTC, mnaguit commented on assets/recorders.csv
> +Canterbury Seismic Instruments,EQR120,46426,,
no need for this entry?

2024-06-12 23:36 UTC, mnaguit commented on install/recorders.csv
> +Canterbury Seismic Instruments,EQR120,EQR120,46426,WQAB,2G,10,,0,0,2024-05-22T02:22:00Z,9999-01-01T00:00:00Z
serial number is `46526`

2024-06-13 02:02 UTC, Thomas-Benson commented
Fixed mistake in serial numbers @mnaguit

2024-06-13 02:07 UTC, mnaguit approved these changes

2024-06-13 03:22 UTC, CBurton90 approved these changes

2024-06-13 20:02 UTC, merged

2024-06-13 20:02 UTC, Thomas-Benson commented
Delta merged