Closing NZF site 42
GeoNet/delta pull request #2115
Opened 2024-06-21 05:07 UTC by EvanCGNS

Changed the end time and date for NZF (site 42) to 2024-07-02T00:00:00Z UTC (12pm, Tuesday 2nd July NZST).

Applied this change to gauges, recorders, streams, firmware, and sites files.

NOTE: All closing times will be updated to the exact time after deployment (in the re-opening ticket). This pre-deployment merge is to block Tilde data ingestion only.

2024-06-23 20:27 UTC, salichon approved these changes
legit

2024-07-02 03:57 UTC, ozym commented
There's a change to NZG as well in `recorders.csv` which needs clarification.

2024-07-02 03:58 UTC, ozym requested changes
There's a change to NZG as well in `recorders.csv` which needs clarification.

2024-07-02 03:58 UTC, ozym commented on install/recorders.csv
> -SAIC,BPR Subsystem,BPR Subsystem,56951,NZG,42,0,,0,0,2024-06-22T23:30:00Z,9999-01-01T00:00:00Z
should this be removed?

2024-07-02 04:00 UTC, EvanCGNS commented on install/recorders.csv
> -SAIC,BPR Subsystem,BPR Subsystem,56951,NZG,42,0,,0,0,2024-06-22T23:30:00Z,9999-01-01T00:00:00Z
Just fixed it, my mistake

2024-07-02 04:01 UTC, ozym approved these changes
looks good

2024-07-02 05:04 UTC, closed without merging