TRVZ install new infrasound sensor
GeoNet/delta pull request #2304
Opened 2024-11-27 01:51 UTC by Thomas-Benson

Adding new Chaparral Physics M64Vx2 (413282) 1t TRVZ
Sensor is at a new location code 31
Assuming the same coordinates as the other infrasound sensor it is installed in parallel with:
-39.298816259, 175.547821602, 2062

2024-12-05 02:07 UTC, salichon commented on install/streams.csv
@Thomas-Benson We re missing the LDF 1hz  i reckon as it is streamed :)

2024-12-05 02:08 UTC, salichon requested changes
one more LD stream :)

2024-12-06 00:47 UTC, salichon approved these changes
sweet thanks!

2024-12-16 00:35 UTC, CBurton90 approved these changes

2025-01-13 22:10 UTC, merged