TEMO: add M16 camera installation under new site and view codes as pe…
GeoNet/delta pull request #884
Opened 2020-08-18 22:26 UTC by staylorofford

…r new camera site code conventions; no change is made to T metadata beyond closing the site.

2020-08-18 23:25 UTC, rumachan approved these changes

2020-08-18 23:32 UTC, Camasher approved these changes

2020-08-19 00:28 UTC, ozym commented
@staylorofford looks like an alphabetical thing going on in the files, the TEMO entry needs to move down the lists a bit.

2020-08-19 22:47 UTC, staylorofford commented
@ozym a rookie error, my bad. I have corrected the ordering and will squash and merge once reviewed.

2020-08-19 23:21 UTC, ozym requested changes
should be good to go, will update XX when known.

2020-08-19 23:21 UTC, ozym approved these changes

2020-08-19 23:46 UTC, merged