LPLS Lake Paringa is Closed 2020
GeoNet/delta pull request #890
Opened 2020-08-28 03:39 UTC by salichon

Instrumentation back in 2020 / last data from 2015

2020-08-28 03:49 UTC, CBurton90 submitted a review, later dismissed
LGTC!

2020-08-31 01:34 UTC, mnaguit requested changes
Closing date/time for station and site is good (2020-08-05) which corresponds to the removal of recorder on site.
How about for the closing of the streams? Shall we use the date/time that corresponds to the last available data (e.g. 2014-10-27T22:41)?

2020-09-03 03:29 UTC, salichon commented
Heya @mnaguit 
I took the last bit of digital file present in the archive that is from  early 2015
if you prefer having it closed over the last recorded data digital  it is all goos yeap. so i make the streams closed at 2014-10-28T00:00:00

2020-09-03 22:55 UTC, mnaguit approved these changes

2020-09-04 03:50 UTC, merged