PRNS new station
GeoNet/delta pull request #934
Opened 2020-11-02 03:13 UTC by mnaguit

New strong motion station. Data started streaming on 2020-10-07/23:21UTC.

2020-11-02 20:47 UTC, CBurton90 requested changes
`Internal GPS Clock` instead of `Internal GPS Device` 

Apart from that all good!

2020-11-02 20:56 UTC, CBurton90 approved these changes

2020-11-04 22:37 UTC, salichon approved these changes
looks good to me thanks

2020-11-04 23:08 UTC, mnaguit commented
Hi @ozym .
Do the metadata for this new station look accurate? Thanks.

2020-11-04 23:10 UTC, ozym approved these changes

2020-11-04 23:31 UTC, merged