GNSS RLTN receiver and antenna swap
GeoNet/delta pull request #939
Opened 2020-11-06 01:33 UTC by megankortink

@elidana please double check height in antennas.csv

2020-11-06 03:06 UTC, elidana requested changes
Hi @megankortink , can you please change the order of the receivers file so that entries are ordered by receiver make, model, serial number, and deployment time?
thanks! :)

2020-11-06 03:06 UTC, elidana commented on install/receivers.csv
> +Trimble Navigation Ltd.,TRIMBLE NETR9,5034K69675,RLTN,2020-11-03T00:27:08Z,9999-01-01T00:00:00Z
please shift down this line (entry after 5034K69675 was undeployed from WAHU)

2020-11-06 03:10 UTC, elidana approved these changes
looks good! well done!!!

2020-11-06 03:23 UTC, elidana approved these changes

2020-11-09 20:23 UTC, CBurton90 approved these changes
Looks good!

2020-11-09 21:44 UTC, merged