Remove whakatane camera from cabinet and put on pole
GeoNet/delta pull request #953
Opened 2020-11-24 01:31 UTC by Camasher

2020-11-24 18:31 UTC, rumachan requested changes
There is an image from the pole mounted camera at 05:20, yet the new start time is listed as 05:50. Can you correct this please.

2020-12-09 00:53 UTC, rumachan submitted a review, later dismissed
All good

2021-02-03 20:54 UTC, Camasher commented
@rumachan @JonoHanson ready to merge, I dont have delta merge permissions

2022-02-11 01:01 UTC, rumachan commented
I don't understand how to deal with this

2022-08-26 05:22 UTC, rumachan commented
Checks have passed so didn't do a review.
Checked the images in the archive and they match the time of change in the PR, so all go.

Thanks for dragging this out of the back cupboard @ozym

2025-09-26 00:42 UTC, closed without merging